### ISSUE TITLE
lse

### ISSUE THREAD

**Issue by erayerdin** [erayerdin/altbinutils#13]
**App Name:** lse
**Short Description:** Lists entries (files and directories) in a directory.

# Specification

## Usage

```bash
lse
lse dir/

lse --include-hidden
lse --ih
lse -j
lse --include-dirs
lse --id
lse -d
lse --include-files
lse --if
lse -f

lse --exclude-hidden
lse --eh
lse --xh
lse -J
lse --exclude-dirs
lse --ed
lse --xd
lse -D
lse --exclude-files
lse --ef
lse --xf
lse -F

lse -jdfJDF

lse --size-greater-than
lse --size-gt
lse --sgt
lse --gt
lse --size-less-than
lse --size-lt
lse --slt
lse --lt

lse --older-than
lse --ot
lse --newer-than
lse --nt
```

## Configuration

```toml
version=1

[root.filters.include]
hidden=false
dirs=true
files=true

[root.filters.exclude]
hidden=true
dirs=false
files=false

# all in bytes
[root.filters.size]
greater_than=0
less_than=0

[root.filters.date]
older_than="now"
newer_than="now"
```
