### ISSUE TITLE
rme

### ISSUE THREAD

**Issue by erayerdin** [erayerdin/altbinutils#2]
**App Name:** rme
**Short Description:** Removes files and directories from filesystem.

 - Removes entries (files or directories) from filesystem.
 - By default, it will move entries to trash. This behavior can be changed by configuration.
 - It will move out of trash.
 - It will support automatic deletion of entries bigger than `x` or older than `x`.
 - It won't ask for confirmation if it's deleting a directory. This behavior can be changed by configuration.
 - It will clear trash.

# Specification

## Usage

```bash
rme file.txt
rme dir/
rme file.txt dir/ file2.txt

# total delete
rme file.txt --purge
rme file.txt -p

# move out of trash
rme undo file.txt

# clear trash
rme clear
```

## Configuration

```toml
[root]
# will purge an entry by default if true
purge = false
# exits on fail when removing multiple
exit_on_fail = false

[autodelete]
bigger_than = 0  # in megabytes
older_than = 0  # in days
```
