### ISSUE TITLE
[AltEP-2]: mkent

### ISSUE THREAD

**Issue by erayerdin** [erayerdin/altbinutils#3]
# 1. Introduction

`mkent`, stands for "make entry", is a utility that helps you create files and directories.

# 2. Features

 - [ ] It will help you create files and directories in a single command with the help of a flag.
 - [ ] It will support templates. For instance, you can create (i) a Rust module directory as in `directory/mod.rs`, a Python module directory as in `directory/__init__.py` for directory templates *or* (ii) an empty office file, an empty archive for file templates.
 - [ ] It will support template contexts so that you can fill your `__version__`, `__author__` variables or insert license headers in a Python module directory or file template.
 - [ ] It will change CWD (current file directory) to newly created directory on demand, with flags or predefined configurations.

# 3. Specifications

Specifications are given as examples.

## 3.1 Flags

```bash
##########
# Simple #
##########

# Files #
mkent file.txt
mkent foo/bar/baz.txt

# Directories #
mkent foo --dir
mkent foo -d
mkent foo/bar/baz -d

############
# Template #
############

# Files #
mkent template foo.py --name py
mkent template foo.py -n py
mkent template foo.py -n py --context "author=Eray Erdin;version=0.1.0"
mkent template foo.py -n py -c "license=gpl3"
mkent t foo.py --name py

# Directories #
mkent t package -n py --dir  # package/__init__.py
mkent t package -n py -d
mkent t foo/bar/baz -n py -d  # foo/bar/baz/__init__.py
mkent t foo/bar/baz -n py -d --foreach  # foo/__init__.py, foo/bar/__init__.py, foo/bar/baz/__init__.py
mkent t foo/bar/baz -n py -d -f  # shorthand for --foreach

# Templating #
mkent get-template "https://github.com/foo/bar"  # for file or directory templates
mkent get-template "https://gist.github.com/foo/bar"  # for file templates
mkent get-template foo/bar  # search for and install template
mkent rm-template github/foo/bar
mkent rm-template foo  # will warn you delete a template in root template directory
mkent rm-template foo --yes  # won't warn you
mkent rm-template foo -y  # shorthand for --yes
mkent upd-template gist/foo/bar
mkent list-template
mkent list-templates  # alias for list-template
mkent list-templates --root  # show only the ones installed to root template directory
mkent list-templates --providers  # show only the ones installed by providers
mkent list-templates -rp  # shorthands for --root and --providers, same as nothing
mkent init-template mytemplate
mkent inst-template
mkent inst-template mytemplate  # installs template from "mytemplate" folder in cwd
```

## 3.2 Configurations

```toml
# Serial version of mkent config file
# Used for determining backwards compatibility so that no update breaks the program
version = 1

# Allows recursive creation of directories.
allow_recursive_dirs = true

[template]
# Default for template --name flag
default_file_template = "plain"
# Default for template --name flag with --dir
default_directory_template = "plain"
# Appends to --context
append_context = ""
# Default for template --foreach flag with --dir
foreach = false
# Check updates for provided templates on start of "template" subcommand
check_updates=false

# Appends context for a template
[template.append_context_if]
# py = "license=apache2"

[templating]
# when used "mkent get-template foo/bar", order is important
search_providers = ["github", "gist"]  # more: gitlab, bitbucket
# to be used in home configs
append_search_providers = []
# aliases of providers.
# if template is fetched from "https://github.com/foo/bar"
# it will install to "github/foo/bar"
# also, it is used in upd-template
provider_aliases = [
    ["github", "https://github.com"],
    ["gist", "https://gist.github.com"],
    ["gitlab", "https://gitlab.com"],
    ["bitbucket", "https://bitbucket.com"],
]
```

# 4. Progress Report

 - [ ] `mkent file.txt`
 - [ ] `mkent foo/bar/baz.txt`
 - [ ] `mkent foo --dir`
 - [ ] `mkent template foo.py --name py`
 - [ ] `mkent template foo.py --name py --context "name=johndoe"`
 - [ ] `mkent template foo/bar --name py --dir`
 - [ ] `mkent template foo/bar --name py --context "name=johndoe" --dir`
 - [ ] `mkent template foo/bar --name py --foreach`
 - [ ] `mkent get-template "https://github.com/foo/bar"`
 - [ ] `mkent get-template "https://gist.github.com/foo/bar"`
 - [ ] `mkent rm-template github/foo/bar`
 - [ ] `mkent rm-template foo`
 - [ ] `mkent upd-template github/foo/bar`
 - [ ] `mkent list-templates`
 - [ ] `mkent init-template`
 - [ ] `mkent inst-template`
 - [ ] `mkent inst-template foo`
