### ISSUE TITLE
[AltEP-3]: rment

### ISSUE THREAD

**Issue by erayerdin** [erayerdin/altbinutils#4]
# 1. Introduction

`rment`, stands for "remove entry", is a utility that helps you remove files and directories.

# 2. Features

 - [ ] It will help you remove files and directories in a single command with the help of a flag.
 - [ ] It will remove a directory recursively and without validation from user. User can change this behavior from configurations.
 - [ ] Instead of removing a file or a directory completely, it will move them to *trash*, and yes, this behavior can be later changed by configurations.
 - [ ] It can roll back removed files and directories from trash.
 - [ ] It will support configuration to remove files or directories in trash older than `x` or bigger than `x`.
 - [ ] It will support listing files in trash, and showing especially the files/directory that are removed in CWD (current working directories).

# 3. Specifications

Specifications are given as examples.

## 3.1 Flags

```bash
##########
# Simple #
##########

# Files #
rment file.txt
rment file.txt --purge
rment file.txt -p

# Dirs #
rment foo # removes foo dir
rment foo --yes  # if `confirm_dirs` is set to true, this will bypass the confirmation
rment foo -y

###########
# Listing #
###########
rment list  # shows files/dirs removed in cwd on top
rment list --cwd  # shows only files/dirs

############
# Rollback #
############
rment rollback foo  # get removed file/dir named "foo" back from trash
```

## 3.2 Configurations

```toml
# Serial version of rment config file
# Used for determining backwards compatibility so that no update breaks the program
version = 1

# removes files or directories older than on start
[remove_entries]
files_older_than = 0  # in days. if 0, does nothing.
files_bigger_than = 0  # in megabytest. if 0, does nothing.
directories_older_than = 0
directories_bigger_than = 0

[root]
# if set to true, removes files/dirs completely
purge = false
# if set to true, will ask for confirmation on dirs
confirm_dirs = false

[list]
# only shows removed files and dirs on cwd
cwd_only = false
```

# 4. Progress Report

 - [ ] `rment file.txt`
 - [ ] `rment file.txt --purge`
 - [ ] `rment foo --yes`
 - [ ] `rment list`
 - [ ] `rment list --cwd`
 - [ ] `rment rollback foo`

# 5. Possible Issues

## 5.1 How can one remove a directory/file named after a subcommand?

`list` is a subcommand. What if someone wants to remove a file named `list`? As it's mentioned [here](https://github.com/clap-rs/clap/discussions/2325), they can do `rment -- list`.
