### ISSUE TITLE
[AltEP-4]: mvent

### ISSUE THREAD

**Issue by erayerdin** [erayerdin/altbinutils#5]
# 1. Introduction

`mvent`, stands for "move entry", is a utility that helps you move or copy files and directories.

# 2. Features

 - [ ] It will help you move or copy files and directories in a single command with the help of a flag.
 - [ ] It will use verification with hashing in order to check if the files/directories are not corrupted in the target location, which can be changed with configuration.
 - [ ] It can be used to download files.

# 3. Specifications

Specifications are given as examples.

## 3.1 Flags

```bash
########
# Move #
########
mvent foo.txt bar.txt
mvent foo/ bar/ --yes # will confirm to move directory if `corfirm_dir` is `true`

########
# Copy #
########
mvent copy foo.txt bar.txt
mvent cp foo.txt bar.txt  # alias for copy
mvent cp foo.txt bar.txt --no-verify
mvent cp foo.txt bar.txt -n

############
# Download #
############
mvent download https://foo.bar/baz
mvent dl https://foo.bar/baz  # alias for download
mvent dl https://foo.bar/baz baz.json
```

## 3.2 Configurations

```toml
# Serial version of rment config file
# Used for determining backwards compatibility so that no update breaks the program
version = 1

[root]
confirm_dirs = false

[copy]
verify = true
verification_method = "sha2"  # options: sha2, sha3
```

# 4. Progress Report

 - [ ] `mvent foo.txt bar.txt`
 - [ ] `mvent foo/ bar/`
 - [ ] `mvent foo/ bar/ --no-verify`
 - [ ] `mvent copy foo.txt bar.txt`
 - [ ] `mvent copy foo.txt bar.txt --no-verify`
 - [ ] `mvent download https://foo.bar/baz`
 - [ ] `mvent download https://foo.bar/baz baz.json`

# 5. Possible Issues

## 5.1 How can one remove a directory/file named after a subcommand?

`copy` is a subcommand. What if someone wants to move a file named `copy`? As it's mentioned [here](https://github.com/clap-rs/clap/discussions/2325), they can do `mvent -- copy`.
