### ISSUE TITLE
mke

### ISSUE THREAD

**Issue by erayerdin** [erayerdin/altbinutils#5]
**App Name:** mke
**Short Description:** Creates files and directories.

 - Creates files and directories.
 - Uses template system to create entries.

# Specification

## Usage

```bash
mke file.txt
mke directory

mke file file.txt
mke f file.txt
mke directory dir
mke dir dir
mke d dir

mke file.odt --name libreoffice-writer
mke file.odt -n libreoffice-writer
mke file.odt  # infers the template

mke mod -n python  # creates mod/__init__.py
mke mod -n python --context "version=0.1.0"  # with context
mke mod -n python -c "version=0.1.0"

mke install-template "https://gist.github.com/foo"

mke remove-template foo
mke rm-template foo
mke del-template foo
mke uninstall-template foo

mke list-templates
mke ls-templates
mke ls-templates --builtin
mke ls-templates --thirdparty
```

## Configuration

```toml
[root]
# infers the template from name
# for instance, file.odt results to "libreoffice-writer"
infer_template = true
```
