### ISSUE TITLE
mve

### ISSUE THREAD

**Issue by erayerdin** [erayerdin/altbinutils#6]
**App Name:** mve
**Short Description:** Moves and copies files and directories.

 - Moves and copies files and directories.
 - Uses verification with hashing algorithms.
 - Ability to undo the move or copy.
 - No ask for verification if a directory is moved or copied, unless explicitly defined in configuration.

# Specification

## Usage

```bash
mve file1.txt file2.txt
mve file1.txt file2.txt --copy
mve file1.txt file2.txt -c

mve undo  # lists last operations
mve undo 0  # undo the latest move/copy
mve undo 1 # undo the last second move/copy
```

## Configuration

```toml
[root]
# verify after move or copy operation
verify = true
# algorithm to verify
verify_algorithm = "sha2"
# verify only the first "x" bytes
# used for fast verification
# if 0, verifies the whole file/directory
verify_bytes = 0

[undo]
# maximum undo records
max_record_count = 10
```
